[versions]
kotlin = "2.1.21"
shadow = "9.0.0-beta15"
paper = "1.21.5-R0.1-SNAPSHOT"
userdev = "2.0.0-beta.17"
alert = "1.0.8"

# all ignite related versions
ignite-api = "1.1.0"
sponge-mixin = "0.15.2+mixin.0.8.7"
mixinextras-common = "0.4.1"

[libraries]
alert = { group = "me.obsilabor", name = "alert", version.ref = "alert" }

# all ignite related libraries
ignite-api = { group = "space.vectrix.ignite", name = "ignite-api", version.ref = "ignite-api" }
sponge-mixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "sponge-mixin" }
mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras-common" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }

[bundles]
igniteMod = [
    "ignite-api",
    "sponge-mixin",
    "mixinextras-common"
]